spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ENC(8ZXC1MsW5L30CxbhzL7grNFTm/N7c4c0A+laLFi3+Y6U5zC8NVZLcOnC+zLQvXzVJKgWVtRLtbs+L/ZkqJd0Aw==)
    username: ENC(wVQicImzNxw6ewa53Fy3zw==)
    password: ENC(acC6IwE5qWPyGeH4oikcY+jyEmTP8FTr)
  jpa:
    hibernate:
      ddl-auto: create
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
