spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ENC(gC1LQHZ1vJOkdJibeHFDvpyFbI74WRwyODh12iGI3ioetjnTU5yY5yo1ccR+pid5QsBFJr70vTZqcQDe29KzPkDRPhQBckNAoKvfeDC1+fctkpSKvjcAMGgli4srUNdX)
    username: ENC(cDOWSDL8dFWOZN+L6aSGpw==)
    password: ENC(CEnBYPjZvoQ8KXhgTQh1QcV6Uh0t7OyH)

  jpa:
    hibernate:
      ddl-auto: create
      naming:
        database-platform: org.hibernate.dialect.MySQL8Dialect
